#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh
mkdir 0 > /dev/null 2>&1
cp -r zero/* 0 > /dev/null 2>&1
runApplication setFields
runApplication decomposePar
#runApplication $application
nCpu=`grep "numberOfSubdomains" system/decomposeParDict | awk '{print $2}' | sed "s/;//g"`
runParallel $application $nCpu &

# ----------------------------------------------------------------- end-of-file
